"""Constants for account eligibility and runtime status lifecycles."""

ACCOUNT_READY = "READY"
ACCOUNT_NEEDS_LOGIN = "NEEDS_LOGIN"
ACCOUNT_COOLDOWN = "COOLDOWN"
ACCOUNT_DISABLED = "DISABLED"

RUNTIME_STARTING_BROWSER = "STARTING_BROWSER"
RUNTIME_CONNECTING_RUNTIME = "CONNECTING_RUNTIME"
RUNTIME_WARMING_MODEL = "WARMING_MODEL"
RUNTIME_IDLE = "IDLE"
RUNTIME_BUSY = "BUSY"
RUNTIME_DRAINING = "DRAINING"
RUNTIME_STOPPING = "STOPPING"
RUNTIME_LOST = "LOST"

WARM_RUNTIME_STATUSES = {
    RUNTIME_STARTING_BROWSER,
    RUNTIME_CONNECTING_RUNTIME,
    RUNTIME_WARMING_MODEL,
    RUNTIME_IDLE,
    RUNTIME_BUSY,
}

CAPACITY_RUNTIME_STATUSES = {
    RUNTIME_STARTING_BROWSER,
    RUNTIME_CONNECTING_RUNTIME,
    RUNTIME_WARMING_MODEL,
    RUNTIME_IDLE,
    RUNTIME_BUSY,
    RUNTIME_DRAINING,
}
